# Generated by Django 6.0.1 on 2026-02-05 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed_choice', '0001_initial'),
        ('question', '0002_question_key_points_question_reference_answer'),
        ('useranswer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='feedback',
            new_name='evaluated_feedback',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='score',
            new_name='evaluated_score',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='closed_choice.closedchoice'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question')},
        ),
    ]
