# Generated by Django 6.0.1 on 2026-02-04 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='question.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='one_correct_choice_per_question')],
            },
        ),
    ]
