# Generated by Django 6.0.1 on 2026-02-04 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closed_choice', '0001_initial'),
        ('question', '0003_alter_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='question.question'),
        ),
    ]
