# Generated by Django 6.0.1 on 2026-02-04 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideal_answer', models.TextField()),
                ('key_points', models.JSONField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
    ]
